### PR TITLE
Attempt doc fix.

### PR DESCRIPTION
**Pull request by SamTov**
Removed some redundant dependencies. You still need some of the numpydoc, pandoc, and Jupyter stuff as it is in the docs.

I checked the build by adding the branch to the readthedocs page and it works:

https://py-track.readthedocs.io/en/fix_docs_samtov/index.html

### CODE REVIEW

**Review by SamTov — COMMENTED** [review]
Some requirements may still be removed but are fairly simple. If you really want the doc build to be seperate then could consider adding it to the sphinx makefile. Not sure how it will mess with the CI doc run.

**Review by SamTov — COMMENTED** [review]
Just a small file change.

**Review by PythonFZ — APPROVED** [review]
Looks good.

For now, I like it. But I would suggest adding keeping the `requirements.txt` for e.g., development and tests and add a `requirements-dev.txt` that contains packages that are required for doc building.  In our case they might be identical except for `pytest`.

**Comment by SamTov** [comment]
Okay but not only devs build docs locally. One option that I would suggest we look into is adding a seperate txt file in the docs directory that `pip install -r doc_requirements.txt` is call on during the make command.

**Comment by PythonFZ** [comment]
I don't think we should do this. I would prefer the `doc_requirements.txt` file beside the `requirements.txt` without any changes to the make file. One reason for this is, that when I ssh on a remote machine I sometimes have the wrong pip file in my path. If I did `path/to/correct/pip install -r doc_requirements.txt` there is no issue, but if the script calls it, the packages might be installed in the wrong place.

**Comment by SamTov** [comment]
Sure. Although that seems like a case where we could also add a flag as you would definitely know that your pip is wrong.

**Pull request merged**
